title: Elavarasi Chinnappa # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: Welcome to my GitHub profile! I'm a passionate and seasoned Senior Software Developer with a strong focus on web application development using ASP.NET MVC, C#, and .NET Core. With [X+] years of hands-on experience in the software industry, I've had the privilege of contributing to numerous successful projects and collaborating with talented teams to deliver high-quality solutions. # your text below (remove <br> elements if you don't need line breaks)
 <br><br>
 .NET Developer, Dublin, Ireland
  <br><br>
  <a href="mailto:elavarasi.chinnappa184@gmail.com">vjayakumarjk@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/elavarasi-chinnappa-0bb74918">LinkedIn Profile</a>
  <br>
  theme: jekyll-theme-minimal
