title: Elavarasi Chinnappa # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: >  # your text below (remove <br> elements if you don't need line breaks)
 <br><br>
 Experienced Senior Software Developer | ASP.NET MVC | C# | .NET Core | Sitecore
  <br><br>
  <a href="mailto:elavarasi.chinnappa184@gmail.com">elavarasi.chinnappa184@gmail.com </a>
  <br>
  <a href="http://www.linkedin.com/in/elavarasi-chinnappa">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/elavarasi-chinnappa">Github</a> 
