title: Elavarasi Chinnappa # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <br><br>
 .NET Developer, Dublin, Ireland
  <br><br>
  <a href="mailto:elavarasi.chinnappa184@gmail.com">vjayakumarjk@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/elavarasi-chinnappa-0bb74918">LinkedIn Profile</a>
  <br>
